use crate::export::InstanceDef;
/// Type-level identity of a statically declared archetype.
/// Implemented by the types generated by define_archetypes!.
/// Never instantiated, used only as a type parameter.
/// 
use super::prelude::{ArchetypeId, ArchetypeBundle};
pub use crate::fast_bit::FastBit;
use crate::reg_loc::RegisteredLocation;

/// metadata for a unit struct archetype generated at compile time in include_archetypes!
pub trait ArchetypeMarker: RegisteredLocation + Send + Sync + 'static {
    /// the dense archetype ID assigned by include_archetypes! in declaration order
    const ARCHETYPE_ID: ArchetypeId = Self::DENSE_INDEX;

    /// The set of all components in this archetype.
    /// Built at compile time using FastBit::with().
    const COMPONENT_SET: FastBit;
    
    /// the bundle type used to spawn this archetype.
    /// exactly one field per component, in declaration order
    type Bundle: ArchetypeBundle<Marker = Self>;
    const INSTANCE_DEF: InstanceDef = InstanceDef::UNREGISTERED;
}