/// a struct holding exactly the initial component values for one archetype
/// Generated by include_archetypes!, never implemented manually

pub use super::prelude::{ArchetypeMarker, Archetype};
pub trait ArchetypeBundle: Send + 'static {
    /// The archetype this bundle belongs to
    type Marker: ArchetypeMarker<Bundle = Self>;

    /// Write all component values into the archetype's columns at `row`
    /// # Safety: `archetype` must be Self::Marker's archetype; `row` must be freshly allocated
    unsafe fn write_into_archetype(self, archetype: &mut Archetype, row: usize);
}